apiVersion: apps/v1
kind: Deployment
metadata:
    name: postgres-deployment
    namespace: conmansys
    labels:
        app: postgres
        tier: backend
spec:
    selector:
        matchLabels:
            app: postgres
    template:
        metadata:
            labels:
                app: postgres
                tier: backend
        spec:
            containers:
                - image: postgres
                  name: postgres
                  imagePullPolicy: Always
                  env:
                      - name: POSTGRES_USER
                        valueFrom:
                            configMapKeyRef:
                                name: conmansys-config
                                key: postgres_user
                      - name: POSTGRES_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: conmansys-secret
                                key: postgres_password
                  ports:
                      - name: postgres
                        containerPort: 5432
                  volumeMounts:
                      - name: postgres-storage
                        mountPath: /var/lib/postgresql/data
            volumes:
                - name: postgres-storage
                  persistentVolumeClaim:
                      claimName: postgres-pv-claim
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: pgadmin-deployment
    namespace: conmansys
    labels:
        app: pgadmin
        tier: backend
spec:
    selector:
        matchLabels:
            app: pgadmin
    template:
        metadata:
            labels:
                app: pgadmin
                tier: backend
        spec:
            containers:
                - image: dpage/pgadmin4
                  name: pgadmin
                  imagePullPolicy: Always
                  env:
                      - name: PGADMIN_DEFAULT_EMAIL
                        valueFrom:
                            configMapKeyRef:
                                name: conmansys-config
                                key: pgadmin_default_email
                      - name: PGADMIN_DEFAULT_PASSWORD
                        valueFrom:
                            secretKeyRef:
                                name: conmansys-secret
                                key: pgadmin_default_password
                  ports:
                      - name: pgadmin-port
                        containerPort: 80
