apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: conmansys
spec:
    selector:
        app: postgres
        tier: backend
    type: NodePort
    ports:
        - name: postgres
          protocol: TCP
          port: 5432
          targetPort: postgres
---
apiVersion: v1
kind: Service
metadata:
    name: pgadmin-service
    namespace: conmansys
spec:
    selector:
        app: pgadmin
        tier: backend
    type: NodePort
    ports:
        - name: pgadmin
          protocol: TCP
          port: 80
          targetPort: pgadmin
