apiVersion: v1
kind: Service
metadata:
    name: postgres-service
    namespace: conmansys
spec:
    selector:
        backend: postgres
    type: NodePort
    ports:
        - name: pgadmin
          protocol: TCP
          port: 80
          targetPort: pgadmin-port
        - name: postgres
          protocol: TCP
          port: 5432
          targetPort: postgres
