apiVersion: apps/v1
kind: Deployment
metadata:
    name: confservice-deployment
    namespace: conmansys
spec:
    selector:
        matchLabels:
            app: confservice
    template:
        metadata:
            labels:
                app: confservice
        spec:
            containers:
                - image: confservice
                  name: confservice
                  imagePullPolicy: Never
                  env:
                      - name: DBHOST
                        valueFrom:
                            configMapKeyRef:
                                name: conmansys-config
                                key: postgres_host
                      - name: DBPORT
                        valueFrom:
                            configMapKeyRef:
                                name: conmansys-config
                                key: postgres_port
                      - name: DBUSER
                        valueFrom:
                            configMapKeyRef:
                                name: conmansys-config
                                key: postgres_user
                      - name: DBPASS
                        valueFrom:
                            secretKeyRef:
                                name: conmansys-secret
                                key: postgres_password
                      - name: DBNAME
                        valueFrom:
                            configMapKeyRef:
                                name: conmansys-config
                                key: postgres_name
                  ports:
                      - name: confservice
                        containerPort: 8080
                
