apiVersion: batch/v1
kind: Job
metadata:
    name: conmansys-job
    namespace: conmansys
spec:
    template:
        metadata:
            labels:
                job: conmansys
        spec:
            restartPolicy: OnFailure
            containers:
                - image: conmansys
                  name: conmansys
                  imagePullPolicy: Never
                  env:
                      - name: POSTGRES_HOST
                        valueFrom:
                            configMapKeyRef:
                                name: conmansys-config
                                key: postgres_host
                  ports:
                      - name: conmansys
                        containerPort: 8080
