apiVersion: v1
kind: Service
metadata:
    name: frontend-service
    namespace: conmansys
spec:
    selector:
        app: frontend
    type: NodePort
    ports:
        - protocol: TCP
          port: 80
          targetPort: frontend
