apiVersion: v1
kind: Service
metadata:
    name: confservice-service
    namespace: conmansys
spec:
    selector:
        app: confservice
    type: NodePort
    ports:
        - protocol: TCP 
          port: 8080 
          targetPort: confservice

