apiVersion: v1
kind: Service
metadata:
    name: conmansys-service
    namespace: conmansys
spec:
    selector:
        app: conmansys
    type: NodePort
    ports:
        - protocol: TCP 
          port: 8080 
          targetPort: conmansys

