apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: postgres-pv-claim
    namespace: conmansys
spec:
    accessModes:
        - ReadWriteOnce
    resources:
        requests:
            storage: 5Gi
